# https://docs.astral.sh/uv/guides/integration/github/#publishing-to-pypi

name: Publish to PyPI

on:
  push:
    tags:
      # Publish on any tag starting with a `v`, e.g., v0.1.0
      - v*

jobs:
  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest

    environment:
      name: pypi
    
    permissions:
      id-token: write
      contents: read
    
    steps:
      - uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"

      - name: Install uv with caching enabled
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
      
      - name: Build package
        run: uv build
      
      - name: Publish package
        run: uv publish